DROP DATABASE IF EXISTS CS;
CREATE DATABASE CS;
USE CS; 
DROP TABLE IF EXISTS FACULTY;
CREATE TABLE FACULTY
(id INT,
 name VARCHAR(30),
 age INT,
 PRIMARY KEY(id)
);
LOAD DATA LOCAL INFILE 'c:\\SQL\\faculty.txt' INTO TABLE FACULTY;
